      - name: Compile GMpro Firmware
        run: |
          # 1. Cari file .ino secara otomatis
          SKETCH_PATH=$(find . -name "*.ino" | head -n 1)
          SKETCH_DIR=$(dirname "$SKETCH_PATH")
          
          if [ -z "$SKETCH_PATH" ]; then
            echo "Error: File .ino tidak ditemukan!"
            exit 1
          fi
          
          echo "Menemukan sketch di: $SKETCH_PATH"
          echo "Direktori sketch: $SKETCH_DIR"

          # 2. Jalankan kompilasi dengan menyertakan direktori sketch sebagai library
          # Ini agar file .h seperti EEPROMHelper.h ikut terbaca
          arduino-cli compile --fqbn deauther:esp8266:generic:eesz=4M2M \
          --library "$SKETCH_DIR" \
          "$SKETCH_PATH" \
          --output-dir ./build
